openapi: 3.1.0
info:
  title: Recetas Electronicas - OpenAPI 3.1
  description: |-
    API for managing electronic prescriptions

    links:
    - [Repositorio](https://github.com/CoopTera/RecetasElectronicas)
  version: 1.0.0
externalDocs:
  description: Laravel
  url: https://laravel.com/docs/11.x
servers:
  - url: 'localhost:8000'
tags:
- name: user
- name: patient
- name: recipe
- name: prescription
paths:
  /users:
    post:
      tags:
      - user
      summary: Register a user.
      parameters:
      - in: header
        name: user
        schema:
          type: string
        required: true
        description: user name of the user
      - in: header
        name: password
        schema:
          type: string
        required: true
        description: password
      - in: header
        name: confirm_password
        schema:
          type: string
        required: true
        description: password
      - in: header
        name: phone_number
        schema:
          type: string
        required: true
        description: phone_number
      - in: header
        name: role
        schema:
          type: string
          enum:
            - clinic
            - professional
        required: true
        description: phone_number
      responses:
        "200":
          description: User register successfully
        "400":
          description: Passwords do not match
        "422":
          description: Username already exists
  /users/{user_id}/profile:
    post:
      tags:
        - user
      summary: Fill data for a new registered user.
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
        description: "id of the user that will modify"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ProfileProfessional'
              - $ref: '#/components/schemas/ProfileClinic'

  /patients/{id}:
    get:
      tags:
      - patient
      summary: get patient by id
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric ID of the patient
      responses:
        "200":
          description: data of patient
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int
                    examples:
                    - 1
                    - 99
                  profile:
                    type: object
                    properties:
                      first_name:
                        type: string
                        examples:
                        - juan
                      last_name:
                        type: string
                        examples:
                        - diaz
                      document_type:
                        type: string
                        examples:
                        - dni
                      document_number:
                        type: string
                        examples:
                        - "40234543"
                      telephone:
                        type: string
                        format: Numeric
                        examples:
                        - "3414564323"
                      email:
                        type: string
                        format: email
                        examples:
                        - user@mail.com
                      date_of_birth:
                        type: string
                        format: date
                        examples:
                        - 01/01/2000
                  medical_coverages:
                    type: array
                    items:
                      type: object
                      properties:
                        plan:
                          type: string
                          examples:
                          - inicial
                        member_number:
                          type: string
                          examples:
                          - a12
                  Observations:
                    type: string
                    examples:
                    - Cumple con las indicaciones
                  state:
                    type: string
                    examples:
                    - active
                    - inactive
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
components:
  schemas:
    ProfileProfessional:
      type: object
      properties:
        profile_picture:
          schema:
            type: string
            contentMediaType: image/png
            contentEncoding: base64
            description: Image on base64
        prefix:
          schema:
            type: string
            enum:
              - Dr.
              - Dra.
            examples:
              - Dr.
              - Dra.
          required: true
        document_type:
          schema:
            type: string
            enum:
              - DNI
              - CUIT
              - CUIL
            examples:
              - DNI
              - CUIT
              - CUIL
          required: true
          description: National Identification Number of the user.
        document_number:
          schema:
            type: integer
          required: true
          description: National Identification Number of the user.
        first_name:
          schema:
            type: string
          required: true
        last_name:
          schema:
            type: string
          required: true
        signature:
          schema:
            type: string
            contentMediaType: image/png
            contentEncoding: base64
          required: true
        logo:
          schema:
            type: string
            contentMediaType: image/png
            contentEncoding: base64
          required: true
        address:
          schema:
            type: string
          required: true
        personalized_stamp:
          schema:
            type: string
        profession:
          schema:
            type: string
          required: true
        specialty:
          schema:
            type: string
          required: true
        registration_type:
          schema:
            type: string
          required: true
        jurisdiction:
          schema:
            type: string
          required: true
        registration_number:
          schema:
            type: string
          required: true
        national_id_photo:
          schema:
            type: string
            contentMediaType: image/png
            contentEncoding: base64
          required: true
    ProfileClinic:
      type: object

    patient:
      type: object
      properties:
        id:
          type: integer
          format: int
          examples:
          - 1
          - 99
        profile:
          type: object
          properties:
            first_name:
              type: string
              examples:
              - juan
            last_name:
              type: string
              examples:
              - diaz
            document_type:
              type: string
              examples:
              - dni
            document_number:
              type: string
              examples:
              - "40234543"
            telephone:
              type: string
              format: Numeric
              examples:
              - "3414564323"
            email:
              type: string
              format: email
              examples:
              - user@mail.com
            date_of_birth:
              type: string
              format: date
              examples:
              - 01/01/2000
        medical_coverages:
          type: array
          items:
            type: object
            properties:
              plan:
                type: string
                examples:
                - inicial
              member_number:
                type: string
                examples:
                - a12
        Observations:
          type: string
          examples:
          - Cumple con las indicaciones
        state:
          type: string
          examples:
          - active
          - inactive
    profile:
      type: object
      properties:
        first_name:
          type: string
          examples:
          - juan
        last_name:
          type: string
          examples:
          - diaz
        document_type:
          type: string
          examples:
          - dni
        document_number:
          type: string
          examples:
          - "40234543"
        telephone:
          type: string
          format: Numeric
          examples:
          - "3414564323"
        email:
          type: string
          format: email
          examples:
          - user@mail.com
        date_of_birth:
          type: string
          format: date
          examples:
          - 01/01/2000
    medical_coverage:
      type: object
      properties:
        plan:
          type: string
          examples:
          - inicial
        member_number:
          type: string
          examples:
          - a12
